### ISSUE TITLE
part of the slide cut off (le governance, slide 2)

### ISSUE THREAD

**Issue by iherman** [w3c/presentation-viewer#20] opened 2020-05-05 09:13 UTC
The bottom bullet item does not seem to fit on the slide...

**Comment by r12a** [comment] 2020-05-05 12:38
fwiw, i found that the style sheet used for slides in https://www.w3.org/2020/05/AC/talk/i18n is not the same as that used for https://www.w3.org/2020/Talks/ac-slides/i18n/Overview.html#le_goals4.  Specifically, the former introduces .slide ol > li > p:first-child { display:inline; }.

This broke i18n slide 14 by increasing the line height of the subtext, so that the bottom line went below the page height.  I fixed it at the top of my slide page by setting display back to block.

**Comment by bert-github** [comment] 2020-05-05 20:44
It seems the issue is solved. I propose we close it.

(The style sheet assumed that authors would either write `<li>text</li>` or `<li><p>text</p></li>` but not `<li>text1 <p>text2</p></li>`. Maybe too strong an assumption...)

**Closed as completed** 2020-05-06 10:06 UTC
Labels: AC2020
